import { PermissionsEnum } from "../enums/permissions.enum";
import { UserRoleEnum } from "../enums/user-role.enum";

export const rolePermissions: Record<UserRoleEnum, PermissionsEnum[]> = {
    [UserRoleEnum.ADMIN]: [
        PermissionsEnum.READ_PROFILE,
        PermissionsEnum.UPDATE_PROFILE,
        PermissionsEnum.CREATE_MANAGER,
        PermissionsEnum.CREATE_USER,
        PermissionsEnum.READ_USERS,
        PermissionsEnum.DELETE_USER,
        PermissionsEnum.UPDATE_USER_STATUS,
        PermissionsEnum.UPDATE_ADVERT_STATUS,
        PermissionsEnum.READ_ADVERTS,
        PermissionsEnum.READ_ADVERT,
        PermissionsEnum.DELETE_ADVERT,
        PermissionsEnum.READ_BRANDS,
        PermissionsEnum.READ_MODELS,
        PermissionsEnum.CREATE_BRAND,
        PermissionsEnum.CREATE_MODEL,
        PermissionsEnum.READ_BRAND_REQUESTS,
        PermissionsEnum.READ_MODEL_REQUESTS,
        PermissionsEnum.UPDATE_BRAND_REQUEST_STATUS,
        PermissionsEnum.UPDATE_MODEL_REQUEST_STATUS,
        PermissionsEnum.READ_ADVERT_STATISTICS,
    ],
    [UserRoleEnum.MANAGER]: [
        PermissionsEnum.READ_PROFILE,
        PermissionsEnum.UPDATE_PROFILE,
        PermissionsEnum.READ_USERS,
        PermissionsEnum.DELETE_USER,
        PermissionsEnum.UPDATE_USER_STATUS,
        PermissionsEnum.UPDATE_ADVERT_STATUS,
        PermissionsEnum.READ_ADVERTS,
        PermissionsEnum.READ_ADVERT,
        PermissionsEnum.DELETE_ADVERT,
        PermissionsEnum.READ_BRANDS,
        PermissionsEnum.READ_MODELS,
        PermissionsEnum.CREATE_BRAND,
        PermissionsEnum.CREATE_MODEL,
        PermissionsEnum.READ_BRAND_REQUESTS,
        PermissionsEnum.READ_MODEL_REQUESTS,
        PermissionsEnum.UPDATE_BRAND_REQUEST_STATUS,
        PermissionsEnum.UPDATE_MODEL_REQUEST_STATUS,
        PermissionsEnum.READ_ADVERT_STATISTICS,
    ],
    [UserRoleEnum.SELLER]: [
        PermissionsEnum.READ_PROFILE,
        PermissionsEnum.UPDATE_PROFILE,
        PermissionsEnum.DELETE_PROFILE,
        PermissionsEnum.READ_ADVERTS,
        PermissionsEnum.READ_ADVERT,
        PermissionsEnum.READ_OWN_ADVERTS,
        PermissionsEnum.CREATE_ADVERT,
        PermissionsEnum.UPDATE_ADVERT,
        PermissionsEnum.DELETE_ADVERT,
        PermissionsEnum.READ_BRANDS,
        PermissionsEnum.READ_MODELS,
        PermissionsEnum.SEND_BRAND_REQUEST,
        PermissionsEnum.SEND_MODEL_REQUEST,
        PermissionsEnum.MANAGE_ACCOUNT_TYPE,
        PermissionsEnum.READ_ADVERT_STATISTICS,
    ],
    [UserRoleEnum.BUYER]: [
        PermissionsEnum.READ_PROFILE,
        PermissionsEnum.UPDATE_PROFILE,
        PermissionsEnum.DELETE_PROFILE,
        PermissionsEnum.READ_ADVERTS,
        PermissionsEnum.READ_ADVERT,
        PermissionsEnum.READ_BRANDS,
        PermissionsEnum.READ_MODELS,
    ],
};
